d

diff --git a/.github/workflows/securityAlertsReview.yml b/.github/workflows/securityAlertsReview.yml
--- a/.github/workflows/securityAlertsReview.yml
+++ b/.github/workflows/securityAlertsReview.yml
@@ -96,11 +96,6 @@ jobs:
 
               FORMATTED_DISMISS_REASON=$(echo "$DISMISS_REASON" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
 
-              echo "FORMATTED_DISMISS_REASON"
-              echo $FORMATTED_DISMISS_REASON
-              echo "DISMISS_COMMENT"
-              echo $DISMISS_COMMENT
-
               COMMENT_BODY+="🟢 **[View Alert]($ALERT_URL)**\n"
               COMMENT_BODY+="📌 **File:** \`$ALERT_FILE\`\n"
               COMMENT_BODY+="💡 **Issue:** $ALERT_DESCRIPTION\n"
@@ -129,17 +124,23 @@ jobs:
             COMMENT_BODY+="⚠️ **Please provide a dismissal reason for these alerts.**\n\n"
           fi
 
-          COMMENT_BODY="${COMMENT_BODY//$'\n'/'\n'}"  # Ensure newlines are preserved
-          # Update existing comment if found
+          COMMENT_BODY_JSON=$(jq -Rs . <<< "$COMMENT_BODY")
+
           if [[ -n "$EXISTING_COMMENT_ID" ]]; then
-            echo "Updating existing comment ID: $EXISTING_COMMENT_ID"
-            echo "COMMENT_BODY"
-            echo $COMMENT_BODY
-            curl -s -X PATCH -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type: application/json" \
-              -d "{\"body\": $COMMENT_BODY}" \
-              "https://api.github.com/repos/${{ github.repository }}/issues/comments/${EXISTING_COMMENT_ID}"
+            HTTP_RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X PATCH \
+              -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type: application/json" \
+              -d "{\"body\": $COMMENT_BODY_JSON}" \
+              "https://api.github.com/repos/${{ github.repository }}/issues/comments/${EXISTING_COMMENT_ID}")
+
           else
-            curl -s -X POST -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type: application/json" \
-              -d "{\"body\": $COMMENT_BODY}" \
-              "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
+            HTTP_RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST \
+              -H "Authorization: token ${GITHUB_TOKEN}" -H "Content-Type: application/json" \
+              -d "{\"body\": $COMMENT_BODY_JSON}" \
+              "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments")
+          fi
+
+          if [[ "$HTTP_RESPONSE" -ne 200 && "$HTTP_RESPONSE" -ne 201 ]]; then
+            echo "❌ Error: Failed to update PR comment. HTTP Status: $HTTP_RESPONSE"
+            cat response.json
+            exit 1
           fi
